import type { Metadata } from "next";
import "../globals.css";

import { SidebarLayout } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { cookies } from "next/headers";
import React from "react";
import TopMenuBar from "@/components/top-menubar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <TopMenuBar />
      <div className="pt-12 "> {/* TopMenuBarの高さ分のパディングを追加 */}
        <SidebarLayout
          defaultOpen={cookies().get("sidebar:state")?.value === "true"}
        >
          <AppSidebar />
          {children}
        </SidebarLayout>
      </div>
    </>
  );
}
