import type { Metadata } from "next";
import "../globals.css";

import { SidebarLayout, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/navigation/app-sidebar";
import { cookies } from "next/headers";
import React from "react";
import TopMenuBar from "@/components/navigation/top-menu-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  return (
    <>
      <TopMenuBar />
      <div className="pt-12">
        <SidebarLayout
          defaultOpen={cookieStore.get("sidebar:state")?.value === "true"}
        >
          <AppSidebar />
          <main className="flex flex-1 flex-col p-2 transition-all duration-300 ease-in-out">
            <div className="h-full rounded-md">
              <div className="fixed left-[calc(var(--sidebar-width)+0.2rem)] top-14 z-10 transition-all duration-300 ease-in-out [[data-sidebar=closed]_&]:left-2">
                <SidebarTrigger />
              </div>
              {children}
            </div>
          </main>
        </SidebarLayout>
      </div>
    </>
  );
}
