import type { Metadata } from "next";

import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import { ChevronDown } from "lucide-react";
import React from "react";
import { ModeToggle } from "./mode-toggle-button";
import { LogoutButton } from "../github-logout-button";
import { NavUserInfo } from "../user-info";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function TopMenuBar() {

  return (
    <header className="fixed top-0 left-0 right-0 z-50 border-b bg-white dark:bg-black bg-opacity-90  dark:bg-opacity-80">
      <div className="w-full flex  justify-between h-12 px-4">
        <div className="flex items-center">
          <span className="flex items-center mr-4">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="mr-2"><path d="M12 14a2 2 0 1 0 0-4 2 2 0 0 0 0 4z" /><path d="M20 14a2 2 0 1 0 0-4 2 2 0 0 0 0 4z" /><path d="M4 14a2 2 0 1 0 0-4 2 2 0 0 0 0 4z" /><path d="M12 8v-2" /><path d="M12 18v-2" /><path d="M18.7 8.7l-1.4-1.4" /><path d="M6.7 6.7l-1.4-1.4" /><path d="M18.7 15.3l-1.4 1.4" /><path d="M6.7 17.3l-1.4 1.4" /></svg>
            <span className="font-bold text-xl tracking-tight font-logo">Demo App</span>
          </span>
          <nav className="hidden md:flex items-center space-x-1">

            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" size="default" className="hover:bg-gray-800">Button1 <ChevronDown className="ml-1 h-3 w-3" /></Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <DropdownMenuItem>menu 1</DropdownMenuItem>
                <DropdownMenuItem>menu 2</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
            <Button variant="ghost" size="default" className="hover:bg-gray-800">Button2</Button>
            <Button variant="ghost" size="default" className="hover:bg-gray-800">Button3</Button>
          </nav>
        </div>
        <div className="flex items-center space-x-2">
          <NavUserInfo />
          <ModeToggle />
          {/* <Button variant="ghost" size="sm">Log In</Button> */}
          <LogoutButton />
          {/* <Button variant="secondary" size="sm">Sign Up</Button> */}
        </div>
      </div>
    </header>
  );
}
